### ISSUE TITLE
Broken plugins with addition of `dynamic` field

### ISSUE THREAD

**Issue by rsbondi** [niftynei/glightning#12]
Moved from [here](https://github.com/ElementsProject/lightning/issues/2869)

**Comment by darosior** [comment]
I think adding a boolean startup field to :
```
type Config struct {
	LightningDir string `json:"lightning-dir"`
	RpcFile      string `json:"rpc-file"`
}
```
might fix your issue.

**Comment by rsbondi** [comment]
Yes, that seems to fix, I was already on it, just need to check that it won't break older clightning versions and will submit
