### ISSUE TITLE
Segmentation Fault when option default is empty string

### ISSUE THREAD

**Issue by rsbondi** [niftynei/glightning#2]
`p.RegisterOption(glightning.NewOption("remote-cert", "Server certificate", ""))`

This causes a segmentation fault, I tested without glightning and clightning seems to accept an empty string without issue.  Use case is if cert is present use https else http, as a workaround I can use `" "` and check for that

[ref](https://github.com/rsbondi/clightning-go-plugin/blob/56289a5fdd4dd7628c26eb53d46b09dff8121ea4/remoteRPC/remoteRPC.go)

**Comment by niftynei** [comment]
turns out c-lightning works fine with empty strings for default, but chokes if you don't send up a `default` field at all.
