### ISSUE TITLE
Support for 0.9

### ISSUE THREAD

**Issue by ysangkok** [niftynei/glightning#32]
It seems like the project is not compatible with c-lightning 0.9, [released in August](https://medium.com/blockstream/new-release-c-lightning-0-9-0-e83b2a374183)? Is that right? It would be nice to note that more prominently.

**Comment by Ale1ster** [comment]
Bump. Isn't this still an issue?

**Comment by niftynei** [comment]
Yes, this is behind.

**Comment by ysangkok** [comment]
All right, thanks for the acknowledgement. I'll close this since I stopped using glightning.
